name: HungarianVillager
version: 1.0
main: com.nonkungch.HungarianVillager.HungarianVillager
api-version: 1.21
author: NonKungCh
description: A plugin that gives Hungarian names to villagers based on biome and logs their life events.
